name: Get Branch

on: 
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying branch ${{ github.ref }}"