name: My first workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Run a one-line script
      run: echo "👋 Hello World!"

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: List files in the repository
      run: |
        echo "The repository ${{github.repository}} contains the following files:"
        tree