name: Markdown Output

on: push

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: output markdown
        run: |
          echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
          echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
          echo '<h1>Great feature!</h1>' >> $GITHUB_STEP_SUMMARY